#!/bin/bash
#
# RepoMan
# A tool for manage your ArchLinux repository
#
# Copyright (C) 2008 Andrea Scarpino <bash.lnx@gmail.com>
#                    Dario Vilardi <dax@deelab.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

action=$1
pkg=$2

function environment()
{
  source /etc/repoman.conf
  check_dir
  color
}

function color()
{
  if [ "$NOCOLOR" != "TRUE" ]; then
    DEFA="\033[1;0m"
    BOLD="\033[1;1m"
    LRED="\033[1;31m"
    LGRE="\033[1;32m"
    YELL="\033[1;33m"
  else
    NOCOLOR_FLAG="--nocolor"
  fi
}

function get_file()
{
  printf "${LGRE} $1 ${DEFA}"
  rm -f $workspace/$1
  wget -P $workspace $url/$1 &> /dev/null
  if [ ! -e $workspace/$1 ]; then
    printf "\n${LRED}Impossibile scaricare $1. Termino. ${DEFA}\n"
    exit 0
  fi
}

function get_pkg()
{
  printf "${LGRE} $1.tar.gz ${DEFA}"
  wget -P $workspace/pkg http://aur.archlinux.org/packages/$1/$1.tar.gz &> /dev/null
  if [ ! -e $workspace/pkg/$1.tar.gz ]; then
    printf "\n${LRED}$1 non trovato. Termino. ${DEFA}\n"
    exit 0
  fi
}

function extract()
{
  printf "${LGRE}$1 ${DEFA}"
  rm -rf $workspace/pkg/$1
  tar -xf $workspace/pkg/$1.tar.gz -C $workspace/pkg || return 1

}

function check_dir()
{
  if [ ! -d $workspace ]; then
    mkdir $workspace
  fi
  
  if [ ! -d $workspace/pkg ]; then
    mkdir $workspace/pkg
  fi
}

function build_pkg()
{
  printf "${LGRE} $1"
  cd $workspace/pkg/$1
  pkgver=`cat PKGBUILD | grep pkgver= | awk -F'=' '{print $2}'`
  pkgrel=`cat PKGBUILD | grep pkgrel= | awk -F'=' '{print $2}'`
  pkgver=`echo $pkgver-$pkgrel`
  makepkg -f --noconfirm &> /dev/null || return 1
  printf " ($pkgver)${DEFA}\n"
}

function copy_pkg()
{
  cp $workspace/pkg/$1/$1-$pkgver-$arch.pkg.tar.gz $workspace/
}

function update_db()
{
  printf "${YELL}Aggiorno: ${LGRE}$repo.db.tar.gz${DEFA}\n"
  if [ "$action" = "add" ] || [ "$action" = "update" ]; then
    repo-add $workspace/$repo.db.tar.gz $workspace/$1-$pkgver-$arch.pkg.tar.gz &> /dev/null || return 1
  elif [ "$action" = "remove" ]; then
    printf "${LGRE}$1 ${YELL}rimosso! ${DEFA}\n"
    repo-remove $workspace/$repo.db.tar.gz $1 &> /dev/null || return 1
  fi
}

function update_changelog()
{
  if [ "$NOCHANGELOG" != "TRUE" ]; then
    printf "${YELL}Aggiorno ${LGRE}$1${DEFA}\n"
    echo `date +"%d-%m-%Y %R"` `whoami` > /tmp/temp
    if [ "$action" = "add" ]; then
      flag=A
    elif [ "$action" = "update" ]; then
      flag=U
    elif [ "$action" = "remove" ]; then
      flag=R
    fi
    echo "* $flag $pkg $pkgver" >> /tmp/temp
    echo "" >> /tmp/temp
    cat /tmp/temp $workspace/$changelog > /tmp/$changelog
    mv /tmp/$changelog $workspace/$changelog
  fi
}

function print_help()
{
  printf "RepoMan: A tool for manage your personal ArchLinux repository\n"
  printf "\n"
  printf "Usage: repoman add|update|remove package\n"
}

environment

if [ "$pkg" = "" ]; then
  print_help
  exit 0
fi

printf "${YELL}Scarico i file: "
if [ "$NOCHANGELOG" != "TRUE" ]; then
  get_file $changelog
fi
get_file $repo.db.tar.gz
if [ "$action" = "add" ] || [ "$action" = "update" ]; then
  if [ ! -e $workspace/pkg/$pkg.tar.gz ]; then
    get_pkg $pkg
  fi
fi
printf "\n"

if [ "$action" = "add" ] || [ "$action" = "update" ]; then
  printf "${YELL}Estraggo: "
  extract $pkg
  printf "\n"
  
  printf "${YELL}Compilo: "
  build_pkg $pkg

  copy_pkg $pkg
fi
  
update_db $pkg

update_changelog $changelog

exit 0
